language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: kbdg3TMWJWjMCtGF+/KRHxKKa3wnlH1v0g/Hz+LScTFjNoNHeDOkUQ5UjLY75iVSUeZQkW2CYjCDb7Tzo2sXUWDDTnibYc/38OlDAiAZMak8idlP+7/CDzWHdc7yKEMNKlqzKDKyF8g7OhN/tZrz6BzwcOVLjBLIOAMt9TEI/mqAm1c7aXo8Unl1z6fpQUha6VI1nOCMS6twi7phcEFS2L9Y0cdPK+IquvAEB2PGepXxowgkpZY4yWc9DPDkCopKmuPcLA4PBfjSwtzITg7D98HT9HNfpXHgrQ1YSv/t9R7jsOOoL7FtFBjsg4zPuMrK4uSYCTuG0W5Z1RjwP5qnIm9y3Tt+wH4bCn3fmUG5r8TrQ8dLbtAybJtqr8r62/wuAfWA7OqIAH6BKglXXU865cF6lgkY9PM2rIy1PaJdK/oF1WhxYQ9ASUZkO1bmuioVRF/KBbSdkBx/Eq3C9iBDIXSqCSik22ZDd1TT+Wr4MFVZEy4sK5078YM9JT8yk1yWyfK67sLX/ntYrMBsvg5tF30gbmdbEx3EaF2wSnXzjz9n5rE0FyEfAG9/Ao4cPfCOWZTLGHLcAqC0LAKNfDPCmNmkGYgKG7FiBvEzB+WYyIrS8cEmXtwLpRdGAk6cwSXlMZKT8LUtdU88ng9xtwkeDgjbrEAAViInIk1w35aUSCU=
  app: powergrade-server
  on:
    repo: thinkful-ei22/Jennifer-PowerGrade-Server
